### ISSUE TITLE
[Question]: How do I implement playlists?

### ISSUE THREAD

**Issue by bootleg-icarus** [morinted/rehowl#7]
Firstly, Thank you so much for rehowl, it is so useful and fits right in with react.
So, I wanna create dynamic playlists. I haven't implemented in howler either but I'm assuming you could create a new Howl and keep adding them to an array and use them to play, skip, prev, etc. using user events.
I did check the docs thoroughly and didn't find what I was looking for. Maybe I'm not thinking the right way? Please guide me

**Comment by morinted** [comment]
You could use two useHowls, I think. Swap between them to maintain the
current and next song.

The Play element would be given the current howl until it's over and then
go to the other one. The first instance would then be reused by changing
the SRC array which would kick off loading.

(Assuming dynamic playlist to mean something like randomizing the playing
order of a set of songs)

**Comment by bootleg-icarus** [comment]
Thank you for the quick reply, I got it to work with your suggestion.
