### ISSUE TITLE
Second play of the same sprite ID appears to fail for no apparent reason

### ISSUE THREAD

**Issue by fatuhoku** [morinted/rehowl#8]
Thanks for working on this project. Rehowl is mostly awesome, but I've run up against an annoying bug.

Problem: Playing the same sprite twice immediately after another causes the second time to 'not play' (not sure why).

I'm using sound-sprites to effectively selectively play chunks of an audio file, often times in sequence, one after another. I made my own component to wrap around the idea of sequenced play, rendering one `Play` following the `onEnd` of the previous `Play`.

```
const SequencePlay = ({ sprites = [], onEnd, ...rest }) => {
  const [spritePlaylist, setSpritePlaylist] = useState(sprites)

  return (
    <>
      <p>Current playlist: {JSON.stringify(spritePlaylist)}</p>
      <Play
        sprite={spritePlaylist[0]} // always play the current sprite
        stop={spritePlaylist.length === 0}
        onEnd={() => {
          const nextUpSprites = spritePlaylist.slice(1)
          setSpritePlaylist(nextUpSprites)
          if (nextUpSprites.length === 0 && onEnd) {
            onEnd()
          }
        }}
        {...rest}
      />
    </>
  )
}
```

Usage:
```
  const { howl, state } = useHowl({
    src: soundPath,
    sprite: {
    blast: [0, 3000],
    laser: [4000, 1000]
    },
  })
...
  // somewhere in render()
  <SequencePlay howl={howl} sprites={['blast', 'blast']} /> // second blast doesn't play; onEnd is never called; spritePlaylist state gets stuck forever
  <SequencePlay howl={howl} sprites={['blast', 'laser']} /> // both sprites play fine in succession; spritePlaylist is exhausted and becomes []
```

In order to do two `blast` in succession successfully, I found it's necessary to insert a fake 1ms sprite:

```
useHowl({
    src: soundPath,
    sprite: {
    _gap: [0, 1], // fake gap sprite to allow two same sprite playbacks to succeed
    blast: [0, 3000],
    laser: [4000, 1000]
    }

...
// in render()
  <SequencePlay howl={howl} sprites={['blast', '_gap', 'blast']} /> // sounds like 2 blasts were played in succession, except of course, there really was a 1ms gap.
```

I can't imagine it being a howler.js problem with calling `play()` so I'm going to assume it's a Rehowl problem.

**Comment by fatuhoku** [comment]
Also no error messages were shown at any point, including when an invalid `spriteId` was fed into Howler.js. Was wondering why nothing played...

**Comment by morinted** [comment]
Not at a computer, but one thing to try would be including a key prop on
Play to force a rerender when you are changing sounds. E.g. the index of
the sprite you're playing.

Validating the sprite name might not be in scope as I figure howler would
be responsible for handling that?

**Comment by fatuhoku** [comment]
Hey @morinted thanks for the response. Of course! `key` did the trick to force re-render.
In the case of `['blast', 'blast']` `sprite` is just set from `'blast'` to `'blast'`. So React registers no change to `Play`'s props. No re-render.

In case of sequenced play, I can make things look different every time `Play` completes with `key={spritePlaylist.length}`. This causes `key === 2` on the first playthrough and `key === 1` on the second play through, triggering a re-render. Works perfectly now.

It might just be my React newbness showing but it would be good to document this behaviour in the docs at some point. =]
